### PR TITLE
docs(extras.vscode): update enabled plugins

### PR DESCRIPTION
**Pull request by theol0403**
Update from https://github.com/LazyVim/LazyVim/pull/3250/

### CODE REVIEW

**Comment by folke** [comment]
Those docs are auto-generated every hour, so there will be a new release of the docs soon

**Comment by theol0403** [comment]
Are you sure? This file seems hardcoded.

**Comment by folke** [comment]
Yes I'm sure. All files under plugins are auto-generated. All of them

**Comment by theol0403** [comment]
@folke sorry, it seems like the docs haven't yet been updated. the last commit to the vscode extra doc is 7 months ago, and I can't find any of the strings elsewhere in the LazyVim organization, so I think it missed being automated.

**Comment by folke** [comment]
My bad! Part of the file is of course not auto-generated.
Merged. Thank you!

**Pull request merged**
